### ISSUE TITLE
Doesn't configure() also write the new value into the settings file?

### ISSUE THREAD

**Issue by romanrdgz** [drgarcia1986/simple-settings#75] opened 2018-09-17 09:01 UTC
I'm loading a settings.py file with LazySettings implementation. Variables are read OK. I can set new values with configure, but the new value is only stored in the instance of LazySettings, not in the settings.py file. Therefore, in the next execution of the application, default values are used again.

I haven't found a way to do this in the documentation. Is it possible, or should I do it myself?

**Comment by drgarcia1986** [comment] 2018-09-24 20:27
Hi, the `configure` method affects the current execution and [dynamic storage](https://github.com/drgarcia1986/simple-settings#dynamic-settings), but, simple-settings doesn't update your settings files.

**Comment by romanrdgz** [comment] 2018-09-25 06:00
That's what I thought...

Anyway, is there any easy way of writing a new settings file from the data stored in dynamic storage, so I can do this at the end of the program execution and finally replace settings.py for temp_settings.py?

**Comment by Manix343** [comment] 2018-10-18 19:00
Please say this is possible so that I don't have to write a parser or switch to another system completely.

It seems like `configure` should be able to be passed an arg that tells it to write to file or not!

**Comment by drgarcia1986** [comment] 2018-10-18 20:20
@romanrdgz I can save a JSON file on the end of the program with the content of `settings.as_dict()` and use that file in settings file list, f.ex:
```python
with open('updated_settings.json', 'w') as f:
    f.write(json.dumps(settings.as_dict()))
```
```shell
$ python foo.py --simple-settings=my_settings,updated_settings.json
```
But, for me, this workaround sounds weird.

**Comment by drgarcia1986** [comment] 2018-10-18 20:21
@Manix343 the method `configure` was designed to change settings values in runtime

**Comment by Manix343** [comment] 2018-10-19 09:09
@drgarcia1986 That's clear to me now, but it's not clear in the docs, and I wish it had been, because it's taken me down some unwanted holes. 

Even just what you said to me, pasting that right below the configure example, would be more legit than letting people figure it out halfway through a project.

**Comment by drgarcia1986** [comment] 2018-10-19 16:54
@Manix343 sounds good to me, could you open a pull request with a better explanation about the `configure` method?

**Comment by Manix343** [comment] 2018-10-21 03:52
@drgarcia1986 I could, but I'm still new to using github. For simplicity sake, If you don't mind, here is the updated configure entry:

configure
---------

If you'd like to change any settings (or add new settings), you can do so with
the method ``configure``:

.. code:: python

    >>> settings.SOME_CONF
    foo
    >>> settings.configure(SOME_CONF='bar')
    >>> settings.SOME_CONF
    bar

..

Keep in mind that this only modifies the settings during runtime, and any 
modifications using ``configure`` will be lost on program exit.

    If you're using ``dynamic settings``, the *configure* method will update the settings value in dynamic storage as well.

**Comment by drgarcia1986** [comment] 2018-10-22 16:41
Done ✅ 
Thank you @Manix343

**Comment by drgarcia1986** [comment] 2018-10-22 16:41
@romanrdgz and @Manix343 I'll close this issue

**Closed by drgarcia1986** 2018-10-22 16:41 UTC
